In [72]:
def anketing():
    gauth = GoogleAuth()
    # Try to load saved client credentials
    gauth.LoadCredentialsFile("mycreds.txt")
    if gauth.credentials is None:
        # Authenticate if they're not there
        gauth.LocalWebserverAuth()
    elif gauth.access_token_expired:
        # Refresh them if expired
        gauth.Refresh()
    else:
        # Initialize the saved creds
        gauth.Authorize()
    # Save the current credentials to a file
    gauth.SaveCredentialsFile("mycreds.txt")
    drive = GoogleDrive(gauth)
    tables_root_id = drive.ListFile({'q': "title = 'Таблицы -> Анкеты'"}).GetList()[0]['id']
    file_list = drive.ListFile({'q': " '%s' in parents and trashed = FALSE" % tables_root_id}).GetList()
    for file in file_list:
        if file['title'] == 'Nice2MeetYou':
            print("Файл скачан: "+file['title']+'.xlsx')
            file.GetContentFile(file['title']+'.xlsx', mimetype = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
            nice = pd.read_excel(file['title']+'.xlsx', dtype = str, keep_default_na = False)
            nice.columns = [col.replace(' ', '').replace('/', '').replace('.', '').lower() for col in nice.columns]
            nice['phone'] = nice['phone'].apply(lambda x: '8' + x[2:] if len(x) > 2 else x)
        if file['title'] == 'Cases':
            print("Файл скачан: "+file['title']+'.xlsx')
            file.GetContentFile(file['title']+'.xlsx', mimetype = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
            case = pd.read_excel(file['title']+'.xlsx', dtype = str, keep_default_na = False)
            case.columns = [col.replace(' ', '').replace('/', '').replace('.', '').lower() for col in case.columns]
        if file['title'] == 'Knowledge':
            print("Файл скачан: "+file['title']+'.xlsx')
            file.GetContentFile(file['title']+'.xlsx', mimetype = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
            know = pd.read_excel(file['title']+'.xlsx', dtype = str, keep_default_na = False)
            know.columns = [col.replace(' ', '').replace('/', '').replace('.', '').lower() for col in know.columns]
        if file['title'] == 'Теория технологического предпринимательства - тест.xlsx':
            print("Файл скачан: "+file['title'])
            file.GetContentFile(file['title']) 
            test = pd.read_excel(file['title'], dtype = str, keep_default_na = False)
            test.columns = [col.replace(' ', '').replace('/', '').replace('.', '').lower() for col in test.columns]
            test['ma_email'] = test['e-mail']
    tilda_file = drive.ListFile({'q': "title = 'Группы с тильды'"}).GetList()[0]
    tilda_file.GetContentFile(tilda_file['title']+'.xlsx', mimetype = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    excel_table = pd.ExcelFile(tilda_file['title']+'.xlsx')
    print("Файл скачан: "+tilda_file['title'])
    
    tilda_new_file = drive.ListFile({'q': "title = 'Регистрация онлайн-практикумов 2022'"}).GetList()[0]
    tilda_new_file.GetContentFile(tilda_new_file['title']+'.xlsx', mimetype = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    excel_new_table = pd.read_excel(tilda_new_file['title']+'.xlsx', dtype = str, keep_default_na = False)
    excel_new_table.columns = [col.replace(' ', '').replace('/', '').replace('.', '').lower() for col in excel_new_table.columns]
    excel_new_table['phone'] = excel_new_table['phone'].apply(lambda x: '8' + x[2:] if len(x) > 2 else x)
    print("Файл скачан: "+tilda_new_file['title'])
    
    """
    #tilda_new_file = drive.ListFile({'q': "title = 'Регистрация онлайн-практикумов 2022'"}).GetList()[0]
    #tilda_new_file.GetContentFile(tilda_new_file['title']+'.xlsx', mimetype = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    excel_new_table = pd.read_csv('555.csv', sep=';', dtype = str, keep_default_na = False)
    excel_new_table.columns = [col.replace(' ', '').replace('/', '').replace('.', '').lower() for col in excel_new_table.columns]
    excel_new_table['phone'] = excel_new_table['phone'].apply(lambda x: '8' + x[2:] if len(x) > 2 else x)
    excel_new_table['formname'] = excel_new_table['formname'].apply(lambda x: x.replace(' ', ''))
    #print("Файл скачан: "+tilda_new_file['title'])
    """
    referer_dict = {'ТУСУР': 'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-tusur/test/nice2meetyou',
           'УРФУ': 'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-urfu/test/nice2meetyou',
           'ТюмГУ': 'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-tyumgu/test/nice2meetyou',
           'ТГУ': 'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-tgu/test/nice2meetyou'}
    excel_new_table['referer'] = excel_new_table['formname'].apply(lambda x: referer_dict[x])
    
    url = 'https://10education.ru'
    r = requests.get(url)
    first_list = r.text.split('<br />')
    index_pass = first_list[0].index('/html')
    first_list[0] = first_list[0][index_pass+10:]
    second_list = [string.split(' - ') for string in first_list]
    df = pd.DataFrame(second_list)
    columns_names = {0: 'username', 1: 'email', 2: 'password', 3: 'history_new'}
    data = df.rename(columns=columns_names)
    data['ma_email'] = data['email']
    data = data[:-1]
    print('Данные получены: '+url)
    
    novella_root_id = drive.ListFile({'q': "title = 'НовеллаБД'"}).GetList()[0]['id']
    file_list = drive.ListFile({'q': " '%s' in parents and trashed = FALSE" % novella_root_id}).GetList()
    for file in file_list:
        if file['mimeType'] == 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
            file.GetContentFile(file['title'])
            rules = pd.read_excel(file['title'])
        """
        if file['mimeType'] == 'text/csv':
            file.GetContentFile(file['title'])
            data = pd.read_csv(file['title'], sep = ";", encoding="windows-1251", quotechar = '"')
            data['ma_email'] = data['email']
            data = data[~data['ma_email'].isna()]
            print(len(data))
        """

    return(nice, case, know, test, data, excel_table, excel_new_table)

In [73]:
def make_table(tab_in, key):
    nice, case, know, test, data, excel_table, excel_table_new = tab_in
    result = nice[nice['referer'] == key][['name', 'name_2', 'name_3', 'ma_email', 'phone', 'univer', 'univer_2']]
    #result = result.sort_values('name', ascending=False).drop_duplicates('ma_email').sort_index().reset_index(drop=True)
    result['Анкета'] = result['ma_email'].apply(lambda x: find_if(x, nice, 'ma_email', 0, str))
    result['Кейсы'] = result['ma_email'].apply(lambda x: find_if(x, case, 'case1', 10, str))
    result['Материал'] = result['ma_email'].apply(lambda x: find_if(x, know, 'vybormateriala', 10, str))
    #result['Тест'] = result['ma_email'].apply(lambda x: find_if(x, test, 'score', 0, int))
    result['Новелла'] = result['ma_email'].apply(lambda x: find_if(x, data, 'history_new', 20, str))
    result['Процент'] = result[['Кейсы', 'Материал', 'Анкета', 'Новелла']].apply(lambda x: sum(x), axis=1) * 25

    c_1 = 0
    df_1 = excel_table_new[excel_table_new['referer'] == key]
    for _d in df_1.to_dict(orient="records"):
        if _d['email'] not in result['ma_email'].values:
            result.loc[len(result)] = [_d['name'], _d['name_2'], '', _d['email'], _d['phone'], '', _d['univer'], 0, 0, 0, 0, 0]
            c_1 += 1  
    print('Новых нулевых: {}'.format(c_1))
    
    c_2 = 0
    df_2 = excel_table.parse(values['-KEY-'])
    for name, email in df_2.values:
        if email not in result['ma_email'].values:
            result.loc[len(result)] = [name, '', '', email, '', '', '', 0, 0, 0, 0, 0]
            c_2 += 1  
    print('Старых нулевых: {}'.format(c_2))

    result = result[~result['ma_email'].isin(['test@technospark.ru', 'test@edu.technospark.ru'])]
    
    return result

In [74]:
def find_if(email, table, column, level, type_):
    if type_ == str:
        return (1 if len(table[table['ma_email'].apply(str.lower) == email.lower()][column]) and len(max(table[table['ma_email'].apply(str.lower) == email.lower()][column])) > level else 0)
    else:
        return (1 if len(table[table['ma_email'].apply(str.lower) == email.lower()][column]) and (max(table[table['ma_email'].apply(str.lower) == email.lower()][column])) != level else 0)

In [77]:
from docxtpl import DocxTemplate, InlineImage
from docx.shared import Cm
import pandas as pd
import numpy as np
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
import requests
import re
from string import ascii_letters
import docx2txt
import json
import docx
import os
import time
import datetime
import PySimpleGUI as sg
import time

layout = [
    [sg.Text('Инструкция:\n\
    1) Нажмите "Скачать данные" и авторизируйтесь\n\
    2) Выберите ключ из списка сверху\n\
    3) Скопируйте таблицу личного кабинета с тильды в файл: "Таблица с тильды.txt"\n\
    4) Нажмите "Создать таблицу"')],
    [sg.Text('Ключ'), sg.Combo([], readonly=True, key='-KEY-', size=(8, 10))],
    [sg.Output(size=(88, 20))],
    [sg.Submit('Скачать данные'), sg.Submit('Создать таблицу'), sg.Cancel('Выйти')]
]

window = sg.Window('Отчет о степени прохождения v1.0', layout)
while True:
    event, values = window.read()
    if event in (None, 'Exit', 'Выйти'):
        break
    if event == 'Скачать данные':
        tables = anketing()
        dict_key = {re.findall('ship-(.+)/test', x)[0]: x for x in list(set(tables[0]['referer'].values)) if 'ship' in x}
        window['-KEY-'].update(values=sorted(dict_key.keys()))
    if event == 'Создать таблицу' and values['-KEY-'] != '':
        table = make_table(tables, dict_key[values['-KEY-']])
        table.reset_index(drop=True, inplace=True)
        # DROP TEST
        table = table[~table['ma_email'].str.contains("test|glebtesr|nemalineii")]
        table.drop_duplicates(subset=['ma_email'], keep='last', inplace=True)
        table.insert(0, "№", range(1, len(table) + 1))
        table.to_excel('Вывод/{}_{}.xlsx'.format(values['-KEY-'], \
                                                 datetime.datetime.now().strftime("%y-%m-%d_%H-%M")), index=False)
        print('Создан файл: Вывод/{}:{}.xlsx'.format(values['-KEY-'], datetime.datetime.now().strftime("%y-%m-%d_%H-%M")))
window.close()

In [35]:
excel_new_table = pd.read_csv('555.csv', sep=';', dtype = str, keep_default_na = False)
excel_new_table.columns = [col.replace(' ', '').replace('/', '').replace('.', '').lower() for col in excel_new_table.columns]
excel_new_table['phone'] = excel_new_table['phone'].apply(lambda x: '8' + x[2:] if len(x) > 2 else x)
excel_new_table['formname'] = excel_new_table['formname'].apply(lambda x: x.replace(' ', ''))
excel_new_table['formname'].unique()

array(['ТУСУР', 'УРФУ', 'ТюмГУ', 'ТГУ'], dtype=object)

In [8]:
import pandas as pd
with open('Таблица с тильды.txt', encoding='utf-8') as f:
    list_strings = f.readlines()
names = [list_strings[i-1][:-1] for i, x in enumerate(list_strings) if "@" in x]
emails = [x[:-1] for x in list_strings if "@" in x]
df = pd.DataFrame({'Имя': names, 'Email': emails})
df.to_excel('TT.xlsx', index=False)

In [15]:
for n, item in enumerate(test.split('\n')):
    if len(item) > 1 and item[-2] == ':':
        print(item, test.split('\n')[n+1])

Создано:	 2022-04-18 17:43  GMT+0600 (Восточный Казахстан)
ma_email:	 hloerr@icloud.com
ma_name:	 Валерия Анатольевна Доронина
name:	 Валерия
name_2:	 Доронина
name_3:	 Анатольевна
email:	 hloerr@icloud.com
phone:	 +7 (983) 340-8944
socialmedia:	 https://vk.com/liradoronina
Ваше_учебное_заведение:	 ТГУ
univer:	 2 курс
univer_2:	 Факультет Журналистики
gorodprojivaniya:	 Tomsk
Checkbox_3:	 yes
tilda_formname:	 Анкета "Расскажите о себе"
Refer page:	 https://techpreneur-school.ru/intro-concepts-of-techpreneurship-tgu/test/nice2meetyou

In [84]:
import pandas as pd
df = pd.read_csv('767.csv')
df[df['referer']=='https://techpreneur-school.ru/task1']

,created,ma_email,ma_name,name,name_2,name_3,email,phone,socialmedia,ваше_учебное_заведение,...,vopros_15,vopros_16,vopros_17,vopros_18,vopros_19,vopros_20,case5,case6,case7,casemedia
50,2022-04-05 19:19:36,kopylova.katyusha@yandex.ru,Екатерина,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
790,2022-04-12 20:53:21,borisov20_21@mail.ru,Борисов Ярослав,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1338,2022-04-15 13:48:30,9271258425@mail.ru,Иван,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2115,2022-04-21 15:27:39,ira.grahmez@gmail.com,Ирина Грахмез,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2374,2022-04-22 16:58:08,dimagoldbergb@gmail.com,Дмитрий,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3370,2022-05-02 11:18:35,duckalice@yandex.ru,алиса,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3375,2022-05-02 11:25:50,titovazlata49@gmail.com,Злата,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3387,2022-05-02 12:09:59,duckalice@yandex.ru,алиса,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3400,2022-05-02 12:41:46,duckalice@yandex.ru,алиса,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3587,2022-05-03 11:50:25,titovazlata49@gmail.com,Злата,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3593,2022-05-03 12:15:23,duckalice@yandex.ru,алиса,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [89]:
dff = df[df['referer']=='https://techpreneur-school.ru/test']
dff = dff.dropna(how='all', axis=1)
#dff.rename(columns = {'created': 'sent', 'checkbox': 'Checkbox', 'formname': 'Form name', 'ваше_учебное_заведение': 'Ваше_учебное_заведение'}, inplace = True)
dff.to_excel('gg.xlsx')

In [95]:
url = 'https://10education.ru'
r = requests.get(url)
first_list = r.text.split('<br />')
index_pass = first_list[0].index('/html')
first_list[0] = first_list[0][index_pass+10:]
second_list = [string.split(' - ') for string in first_list]
df = pd.DataFrame(second_list)
columns_names = {0: 'username', 1: 'email', 2: 'password', 3: 'history_new'}
data = df.rename(columns=columns_names)
data['ma_email'] = data['email']
data = data[:-1]
print('Данные получены: '+url)

In [103]:
data

,username,email,password,history_new,ma_email
0,1,2,3,"{""run_1"": {""q0"": ""a1"", ""q1"": ""a1"", ""q2"": ""a1"",...",2
1,test,test,test,"{""run_1"": {""q0"": ""a1"", ""q1"": ""a2"", ""q2"": ""a2"",...",test
2,Вася,123,123,"{""run_1"": {""q0"": ""a1"", ""q1"": ""a1"", ""q2"": ""a1"",...",123
3,Фамилия Имя Отчество Раз Два Три,emailemailemail@email.ru,5,"{""run_1"": {""w1d1"": ""Реформа отдела"", ""q0"": ""a1...",emailemailemail@email.ru
4,Анна Елашкина,elashkina.anna@gmail.com,pomponA2,"{""run_1"": {""w1d1"": ""Реформа отдела"", ""q0"": ""a1...",elashkina.anna@gmail.com
...,...,...,...,...,...
2081,Васильева Ксения Витальевна,kseniyavasileva2003@mail.ru,ksusha569874123,"{""run_1"": {""q0"": ""a1"", ""q1"": ""a1"", ""q2"": ""a1"",...",kseniyavasileva2003@mail.ru
2082,Кудрявцева Екатерина Евгеньевна,kudryavcevakatya26@gmail.com,TG1BMmtD,"{""run_1"": {""q0"": ""a1"", ""q1"": ""a1"", ""q2"": ""a1"",...",kudryavcevakatya26@gmail.com
2083,Ажичаков Александр Андреевич,dudesbrothers@vk.com,bnRqYkUy,"{""run_1"": {""q0"": ""a2"", ""q1"": ""a2"", ""q2"": ""a1"",...",dudesbrothers@vk.com
2084,Айбыков Кирилл Витальевич,aibykovkirill@mail.ru,260159vk,"{""run_1"": {""q0"": ""a1"", ""q1"": ""a1"", ""q2"": ""a1"",...",aibykovkirill@mail.ru
2085,Кириенко Алена Андреевна,kirienko.svet@yandex.ru,d0IUemRu,"{""run_1"": {""w1d1"": ""Встреча с Сашей""}}",kirienko.svet@yandex.ru

In [267]:
df0 = pd.read_excel('children_registrations_reserve.xlsx')

In [279]:
bigdata = pd.concat([df0, dff], ignore_index=True, sort=False)
#bigdata['phone'] = bigdata['phone'].apply(lambda x: "'" + x[:] if not isinstance(x, float) and len(x) > 2 else x)
bigdata.to_excel('gg.xlsx')

In [105]:
dff.rename(columns = {'created': 'sent'}, inplace = True)

array(['https://techpreneur-school.ru/intro-concepts-of-techpreneurship-urfu/test/cases',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-urfu/test/cases#rec416217944',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-tusur/test/cases#rec411606649',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-tusur/test/cases',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-startup/test/cases#rec381343611',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-tgu/test/cases#rec382423868',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-tgu/test/cases'],
      dtype=object)

In [274]:
set(dff.columns) - set(df0.columns)

{'checkbox', 'created', 'formname', 'ваше_учебное_заведение'}

In [275]:
set(df0.columns) - set(dff.columns)

{'Checkbox', 'Form name', 'requestid', 'sent', 'Ваше_учебное_заведение'}

In [245]:
df0['referer'].unique()

array(['https://techpreneur-school.ru/intro-concepts-of-techpreneurship-urfu',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-tusur#rec432408785',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-urfu#rec432409483',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-tyumgu#rec432409937',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-tusur',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-tgu#rec432397253',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-startup#rec438250549',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-startup',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-tyumgu',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-tgu'],
      dtype=object)

In [239]:
df1 = df[~df['referer'].str.contains('cases|nice|knowledge|game|question|test/test')]
df1[~df1['question'].apply(lambda x: not isinstance(x, float))]['referer'].unique()

array(['https://techpreneur-school.ru/intro-concepts-of-techpreneurship-tusur',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-urfu#rec432409483',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-urfu',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-tusur#rec432408785',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-tenedu-registration',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-tyumgu',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-tgu#rec432397253',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-tyumgu#rec432409937',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-startup#rec438250549',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-startup',
       'https://techpreneur-school.ru/test',
       'https://techpreneur-school.ru/task1',
       'https://techpreneur-school.ru/task2',
       'https://techpreneur-school.ru/task3',
       'https://techpreneur-school.ru/v1',
       'https://techpreneur-school.ru/v2',
       'https://techpreneur-school.ru/v3',
       'https://techpreneur-school.ru/v4',
       'https://techpreneur-school.ru/v5',
       'https://techpreneur-school.ru/v6',
       'https://techpreneur-school.ru/v7',
       'https://techpreneur-school.ru/v8',
       'https://techpreneur-school.ru/v9',
       'https://techpreneur-school.ru/v10',
       'https://techpreneur-school.ru/v11',
       'https://techpreneur-school.ru/v12',
       'https://techpreneur-school.ru/v13',
       'https://techpreneur-school.ru/v14',
       'https://techpreneur-school.ru/v15',
       'https://techpreneur-school.ru/v16',
       'https://techpreneur-school.ru/v17',
       'https://techpreneur-school.ru/v18',
       'https://techpreneur-school.ru/v19',
       'https://techpreneur-school.ru/v20',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-tgu'],
      dtype=object)

In [210]:
dff['referer'].unique()

array(['https://techpreneur-school.ru/intro-concepts-of-techpreneurship-tusur/question',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-urfu/question',
       'https://techpreneur-school.ru/intro-concepts-of-techpreneurship-startup/question'],
      dtype=object)

In [208]:
dff ### practice_finish

,created,formid,referer,ma_email,ma_name,checkbox
14,2022-04-18 10:07:45,form418084322,https://techpreneur-school.ru/intro-concepts-o...,egor.demidenko@mail.ru,Егор,NaN
16,2022-04-18 10:38:12,form418084322,https://techpreneur-school.ru/intro-concepts-o...,litvyakovak@yandex.ru,Екатерина Евгеньевна Литвякова,NaN
47,2022-04-18 15:32:21,form418084322,https://techpreneur-school.ru/intro-concepts-o...,anastasya28092003@yandex.ru,Анастасия,yes
51,2022-04-18 16:19:03,form418084322,https://techpreneur-school.ru/intro-concepts-o...,shaburanovroman@mail.ru,Роман,yes
76,2022-04-18 18:49:55,form418084322,https://techpreneur-school.ru/intro-concepts-o...,Gradoboeva_2003@mail.ru,Аня Градобоева,yes
...,...,...,...,...,...,...
1051,2022-04-25 14:02:43,form418084322,https://techpreneur-school.ru/intro-concepts-o...,sanya.govorov.1999@mail.ru,Александр,yes
1073,2022-04-25 15:08:04,form418084322,https://techpreneur-school.ru/intro-concepts-o...,moskovets.katrina@yandex.ru,Екатерина,NaN
1102,2022-04-25 16:43:53,form418084322,https://techpreneur-school.ru/intro-concepts-o...,thecost37@gmail.com,Иван,NaN
1104,2022-04-25 16:54:35,form418084322,https://techpreneur-school.ru/intro-concepts-o...,shaposhnikov1705@mail.ru,Игорь,NaN
1107,2022-04-25 16:59:58,form418084322,https://techpreneur-school.ru/intro-concepts-o...,ilya.degterev@mail.ru,Илья,NaN

In [44]:
import pandas as pd
df1 = pd.read_excel('Урфу прохождение.xlsx', dtype = str, keep_default_na = False)
df2 = pd.read_excel('УРФУ список приглашённых 27.04.xlsx', dtype = str, keep_default_na = False)
df1 = df1[df1['Анкета'] != '0.0']
df1['name'] = df1['name_2'] + ' ' + df1['name'] + ' ' + df1['name_3']
df1['Сеть'] = df1['ma_email'].apply(lambda x: df0[df0['ma_email'].str.lower()==x.lower()]['socialmedia'].max())
df1[['№', 'name', 'ma_email', 'univer', 'phone', 'Сеть']]

,№,name,ma_email,univer,phone,Сеть
0,1.0,Трофимов Никита Вадимович,nikita174trofimov@gmail.com,1.0,8 (996) 597-8221,https://vk.com/iiikila
1,2.0,Ковальчук Дмитрий Сергеевич,dmitriy.kovalchuk.1913@mail.ru,2.0,8 (982) 312-4205,https://vk.com/mitiatitia
2,3.0,Нелюбина Анна Андреевна,hoseernendes23@gmail.com,1 курс магистратуры,8 (982) 747-5593,https://vk.com/a_nelyubina
3,4.0,Козлякова Яна,yana.kozlyakova@mail.ru,3 курс,8 (902) 495-5500,
4,5.0,Светлакова Ксения Игоревна,svetlakova.99@mail.ru,1.0,8 (917) 481-9049,https://vk.com/aturgeneva
...,...,...,...,...,...,...
219,220.0,Лукманова Кира Вадимовна,kiralukmanova@list.ru,3 курс,8 (909) 007-1165,https://vk.com/k.lukmanova
220,221.0,Прокуратова Кристина Юрьевна,kristina.prokuratova@mail.ru,3.0,8 (967) 854-2074,https://vk.com/id223514812
221,222.0,Калина Ирина Евгеньевна,kalina_ir@mail.ru,1.0,8 (908) 048-7125,
222,223.0,Перминова Кристина Андреевна,kristina.a.perminova@gmail.com,2 курс,8 (909) 140-1434,
223,224.0,Зорин Дмитрий Иванович,zorindima2000@mail.ru,1.0,8 (795) 054-7130,https://vk.com/advisor_bell

In [45]:
for _d in df1.to_dict(orient="records"):
    if _d['ma_email'].lower() not in df2['Почта'].str.lower().values:
        df2.loc[len(df2)] = [len(df2)+1, _d['name'], _d['ma_email'], _d['univer'], _d['phone'], _d['Сеть']]
df2

,№,ФИО,Почта,ВУЗ,Телефон,Сеть
0,1,Серов Александр Иванович,goldianmail@yandex.ru,1 курс,+7 (953) 044-0033,https://vk.com/eff3f2e8ed
1,2,Тишков Кирилл Даниилович,kirill.tishkov@internet.ru,3,+7 (929) 858-7937,https://vk.com/kirilltishkov
2,3,Юмагуен Ришат Русланович,rishat2579@mail.ru,3 курс,+7 (982) 112-9169,https://vk.com/vsemoguen
3,4,Таращенко Наталья Алексеевна,nataran2001@mail.ru,3 курс,+7 (958) 879-3842,https://vk.com/hammerhearted
4,5,Белоусов Сергей Алексеевич,serybely4@gmail.com,2 курс,+7 (953) 826-0038,https://vk.com/sergeibelo
...,...,...,...,...,...,...
219,220,Белозеров Денис,denis.belozerov@urfu.me,3.0,8 (982) 607-6922,
220,221,Вовк Андрей Анатольевич,suhomesovo306@gmail.com,3.0,8 (999) 586-1781,https://vk.com/betweenbutter
221,222,Лукманова Кира Вадимовна,kiralukmanova@list.ru,3 курс,8 (909) 007-1165,https://vk.com/k.lukmanova
222,223,Калина Ирина Евгеньевна,kalina_ir@mail.ru,1.0,8 (908) 048-7125,
223,224,Перминова Кристина Андреевна,kristina.a.perminova@gmail.com,2 курс,8 (909) 140-1434,

In [59]:
df2['ВУЗ'] = df2['ВУЗ'].apply(lambda x: x.replace('.0', '') if '.0' in x else x)

In [55]:
df2['ВУЗ'].replace('0', '')

0      1 курс
1           3
2      3 курс
3      3 курс
4      2 курс
        ...
219       3.0
220       3.0
221    3 курс
222       1.0
223    2 курс
Name: ВУЗ, Length: 224, dtype: object

In [60]:
df2.to_excel('12333.xlsx')

In [69]:
q = []
for a in df2['ФИО']:
    if 'тест' in a:
        q.append(a)
q

['тест тест тест']

In [147]:
import pandas as pd
df = pd.read_excel('База сотрудников_20220505_ АБ.xlsx')
df.dropna(subset = ['АБ: типы людей'], inplace=True)
df = df[~df['АБ: типы людей'].isin([' ', '-'])]
df = df[df['Статус сотрудников']=='Сотрудник']
df.fillna('-', inplace=True)
df.sort_values('Фамилия', inplace=True)
#df[['a','b']] = df.groupby(['Фамилия', 'Имя', 'Отчество']).transform(lambda x: ','.join(x))

In [148]:
result = []
dff = pd.DataFrame(columns=['name', 'info'])
for _d in df.to_dict(orient="records")[:]:
    name = _d['Фамилия']+' '+_d['Имя']+' '+_d['Отчество']
    info = _d['Организация']+' ('+_d['АБ: типы людей']+', '+_d['Должность']+')'
    if name in dff['name'].values:
        dff.at[dff.loc[dff['name']==name]['info'].index[0], 'info'] = dff[dff['name']==name]['info'].values[0]+', '+info
    else:
        dff = pd.concat([dff, pd.DataFrame([[name, info]], columns=['name', 'info'])], ignore_index=True)

In [149]:
dff

,name,info
0,Абдуллаев Бобурхон Баходирович,"Артек Брейдинг (менеджер, Коммерческий директор)"
1,Адилов Бауыржан Маратович,"Медика (инженер, Ведущий специалист по регистр..."
2,Акиньшина Алёна Сергеевна,"БиоСпарк (инженер, Научный сотрудник)"
3,Акрамовский Вячеслав Александрович,"Даймонд Лаб (не определено, Генеральный директор)"
4,Алакоз Сергей Николаевич,"ЦТО ТЕХНОСПАРК (инженер, Мастер сборочного уча..."
...,...,...
321,Юлина Анна Никитична,"ТЕХНОСПАРК САППОРТ (инженер, Бухгалтер)"
322,Юношева Валерия Александровна,"Артек Электроникс (инженер, Менеджер по продаж..."
323,Яковлев Дмитрий Александрович,"Солартек (инженер, Генеральный директор)"
324,Якубик Дмитрий Станиславович,"ЦТО ТЕХНОСПАРК (инженер, Слесарь МСР 6 р.)"
325,Якушева Елена Владимировна,"ЦТО ТЕХНОСПАРК (инженер, Инженер-конструктор)"

In [67]:
import pandas as pd
from docxtpl import DocxTemplate, InlineImage
template = DocxTemplate('Формат шаблон.docx')
data = pd.read_excel('таблица раздельное фио.xlsx')
data = data[data['ФИО'].notna()]
data['ФИО'] = data['ФИО'].apply(lambda x: x+'*' if len(data[data['ФИО']==x]['АБ: типы людей'].unique()) > 1 else x)
data['ФИО'] = data['ФИО'].apply(lambda x: x.replace('  ', ' '))
data['ФИО'] = data['ФИО'].apply(lambda x: x.replace('  ', ' '))

In [68]:
c = 1
table_1 = []
df = data[data['АБ: типы людей']=='старший венчуростроитель']
for name in df['ФИО'].unique():
    table_1.append([c, name, df[df['ФИО']==name]['Организация'].str.cat(sep=', ')])
    c += 1

c = 1
table_2 = []
df = data[data['АБ: типы людей']=='младший венчуростроитель']
for name in df['ФИО'].unique():
    table_2.append([c, name, df[df['ФИО']==name]['Организация'].str.cat(sep=', ')])
    c += 1
    
c = 1
table_3 = []
df = data[data['АБ: типы людей']=='практикант']
for name in df['ФИО'].unique():
    table_3.append([c, name, df[df['ФИО']==name]['Организация'].str.cat(sep=', ')])
    c += 1
    
c = 1
table_4 = []
df = data[data['АБ: типы людей']=='менеджер']
for name in df['ФИО'].unique():
    table_4.append([c, name, df[df['ФИО']==name]['Организация'].str.cat(sep=', ')])
    c += 1    
    
c = 1
table_5 = []
df = data[data['АБ: типы людей']=='инженер']
for name in df['ФИО'].unique():
    table_5.append([c, name, df[df['ФИО']==name]['Организация'].str.cat(sep=', ')])
    c += 1    
    
c = 1
table_6 = []
df = data[~data['АБ: типы людей'].isin(['старший венчуростроитель', 'младший венчуростроитель', 'практикант', 'менеджер', 'инженер'])]
for name in df['ФИО'].unique():
    table_6.append([c, name, df[df['ФИО']==name]['Организация'].str.cat(sep=', ')])
    c += 1    
    
context = {'table_1': table_1, 'table_2': table_2, 'table_3': table_3, 'table_4': table_4, 'table_5': table_5, 'table_6': table_6}
template.render(context)
template.save('12.docx')

In [234]:
import pandas as pd
import numpy as np
import requests
import json

df = pd.read_excel('data.xlsx')
df1 = pd.read_excel('Children_task_1 .xlsx')
df2 = pd.read_excel('Children_task_2.xlsx')
df3 = pd.read_excel('Children_task_3.xlsx')

url = 'https://10education.ru'
r = requests.get(url)
first_list = r.text.split('<br />')
index_pass = first_list[0].index('/html')
first_list[0] = first_list[0][index_pass+10:]
second_list = [string.split(' - ') for string in first_list]
dff = pd.DataFrame(second_list)
columns_names = {0: 'username', 1: 'email', 2: 'password', 3: 'history_new'}
data = dff.rename(columns=columns_names)
data['ma_email'] = data['email']
data = data[:-1]
data['email'] = data['email'].str.lower()
df_pkpk = pd.read_html('_сквозной_список_все_личные_счета.html')[0]

def f(df):
    for col in ['Лекция 22.03', 'Лекция 29.03', 'Лекция 05.04', 'Лекция 12.04']:
        df[col] = df[col].apply(lambda x: 5 if x == 'да' else 0)
    return (df)

def f1(x):
    return (
    (1 if x['answer1']=='Зарплата от государства: появилась из собранных с граждан налогов' else 0)
    + (1 if x['answer2']=='Зарплата от бизнесмена: появилась из прибыли от бизнеса' else 0)
    + (1 if x['answer3']=='Плата за пользование собственностью' else 0)
    + (1 if x['answer4']=='Разница между цена продажи товаров и (цена покупки товаров у поставщиков \
+ выплата зарплат сотрудников, налогов и других расходов на ведение бизнеса)' else 0)
    + (1 if x['answer5']=='Разница между ценой покупки акций и ценой продажи этих акций' else 0)
    + (1 if x['answer6']=='Разница между ценой, по которой продает произведенный продукт и \
затратами на его производство' else 0)
    )

def f2(x):
    return(0)

def f3(x):
    return (
    (4 if x['question1']=='3) Голландцы в 16 веке поставили лесопилку, которая доски деревья для строительства кораблей, \
получая энергию от потока воды. Это был первый бизнес, в котором сначала не было машин (пилили люди) , \
а потом лесопилка резко увеличила скорость работы и хозяин строительства получил прибыль.' else 0)
    )

def f4(email):
    if data[data['email'] == email.lower()]['history_new'].to_list() != []:
        h_str = data[data['email'] == email.lower()]['history_new'].to_list()[0]
        h_json = json.loads(h_str)
        h_list = [rec for rec in h_json.values() if rec != {}]
        if h_list == []:
            return 0
        h_record = max(h_list, key=len)
        if 'q39' in h_record.keys() and h_record['q39'] == 'a1' and 'q58' in h_record.keys() and h_record['q58'] == 'a1': 
            return 15
        elif ('q39' in h_record.keys() and h_record['q39'] == 'a1') or ('q58' in h_record.keys() and h_record['q58'] == 'a1'):
            return 5
        else:
            return 0
    else:
        return 0
    
def f5(x):
    if x == 'Инженер':
        return 10
    elif x == 'Предприниматель':
        return 15
    else:
        return 0

s="""Акишева Анна - 40 баллов
Дзгоев Артур - 40 баллов 
Грахмез Ирина - 30 баллов
Васильев Константин - 15 баллов
Борисов Ярослав - 15 баллов
Давидович Дарья - 15 баллов
Сахнов Игнатий - 15 баллов"""

d=dict(item.split(" - ") for item in s.split("\n"))
for key, value in d.items():
    d[key] = int(value.split(' ')[0])
    
def f5_x(x):
    if x['Имя'] in d.keys():
        return max(d[x['Имя']], x['f5'])
    else:
        return x['f5']
    
df = f(df)
df1['f1'] = df1.apply(f1, axis=1)
df['f1'] = df['Контакты '].apply(lambda x: int(np.nanmax([df1[df1['ma_email'].str.lower()==x.lower()]['f1'].max(), 0])))
df['f2'] = 0
df3['f3'] = df3.apply(f3, axis=1)
df['f3'] = df['Контакты '].apply(lambda x: int(np.nanmax([df3[df3['ma_email'].str.lower()==x.lower()]['f3'].max(), 0])))
df['f4'] = df['Контакты '].apply(f4)
df_pkpk['f5'] = df_pkpk['Роль'].apply(f5)
df_pkpk['f5'] = df_pkpk.apply(f5_x, axis=1)
df['f5'] = df['Контакты '].apply(lambda x: int(np.nanmax([df_pkpk[df_pkpk['Контакт'].str.lower()==x.lower()]['f5'].max(), 0])))

df = df[['№', 'ФИО', 'Контакты ', 'Лекция 22.03', 'Лекция 29.03', 'Лекция 05.04', 'Лекция 12.04', 'f1', 'f2', 'f3', 'f4', 'f5']]
df['Сумма баллов'] = df.loc[:,['Лекция 22.03', 'Лекция 29.03', 'Лекция 05.04', 'Лекция 12.04', 'f1', 'f2', 'f3', 'f4', 'f5']] \
    .sum(axis=1)
df.rename(columns={'f1': 'Задание 1', 'f2': 'Задание 2','f3': 'Задание 3','f4': 'Новелла','f5': 'Игра'}, inplace = True)

In [255]:
df.to_excel('Дети тест.xlsx')

In [28]:
df.columns[1]

' ?it/s]'

In [71]:
import pandas as pd
df = pd.read_csv('123.txt', header=[1])
df = df.rename(columns={'  0%|                                                                                          | 0/619 [00:00<?': 'name',' ?it/s]': 'value'})
df=df[::2]
df

                                                  name value
0     Вывод/tusur/2/Шихман Илья Владимирович.docx 19 2   NaN
2    Вывод/tusur/1/Цыремпилов Даниил Баирович.docx ...   NaN
4       Вывод/tusur/1/Килин Никита Андреевич.docx 51 1   NaN
6      Вывод/tusur/1/Савельев Глеб Сергеевич.docx 50 1   NaN
8    Вывод/tusur/1/Склярова Анастасия Владимировна....   NaN
..                                                 ...   ...
968  Вывод/tusur/2/Мурашова Екатерина Вячеславовна....   NaN
970  Вывод/tusur/1/Белозерова Алина Евгеньевна.docx...   NaN
972   Вывод/tusur/2/Сафронов Данил Антонович.docx 30 2   NaN
974  Вывод/tusur/1/Павлюк Анастасия Дмитриевна.docx...   NaN
976  Вывод/tusur/1/Лисовская Иванна Александровна.d...   NaN

[489 rows x 2 columns]

In [74]:
string = ' '.join(df['name'])
string

'Вывод/tusur/2/Шихман Илья Владимирович.docx 19 2 Вывод/tusur/1/Цыремпилов Даниил Баирович.docx 40 1 Вывод/tusur/1/Килин Никита Андреевич.docx 51 1 Вывод/tusur/1/Савельев Глеб Сергеевич.docx 50 1 Вывод/tusur/1/Склярова Анастасия Владимировна.docx 73 1 Вывод/tusur/1/Коновалова Марьяна Александровна.docx 43 1 Вывод/tusur/1/Котенков Иван Алексеевич.docx 40 1 Вывод/tusur/1/Корнякова Ксения Владимировна.docx 62 1 Вывод/tusur/1/Волкожа Анна Михайловна.docx 67 1 Вывод/tusur/1/Лобыня Александр Эдуардович.docx 40 1 Вывод/tusur/2/Маркус Роман Филиппович.docx 17 2 Вывод/tusur/2/Круглов Илья Владимирович.docx 36 2 Вывод/tusur/2/Вашай Анастасия Дмитриевна.docx 37 2 Вывод/tusur/2/Донгак Даяна Демидовна.docx 26 2 Вывод/tusur/1/Титов Игорь Владимирович.docx 61 1 Вывод/tusur/1/Айбыков Кирилл Витальевич.docx 64 1 Вывод/tusur/1/Рязанов Олег .docx 68 1 Вывод/tusur/2/Сычев Иван Александрович.docx 29 2 Вывод/tusur/1/Лучкин Дмитрий .docx 52 1 Вывод/tusur/1/Акимов Владислав Александрович.docx 49 1 Вывод/tusur/2/Петрова Екатерина Вадимовна.docx 27 2 Вывод/tusur/1/Будакова Вероника Никитична.docx 62 1 Вывод/tusur/2/Коц Кристина Викторовна.docx 11 2 Вывод/tusur/2/Сакенов Назар Асхатович.docx 38 2 Вывод/tusur/1/Ушаров Александр Сергеевич.docx 57 1 Вывод/tusur/2/Карманов Арсений Викторович.docx 33 2 Вывод/tusur/2/Дмитриев Роман Дмитриевич.docx 21 2 Вывод/tusur/1/Устинов Владислав Алексеевич.docx 77 1 Вывод/tusur/1/Конюхов Егор Сергеевич.docx 55 1 Вывод/tusur/1/Рабданова Димэд Бальжинимаевна.docx 62 1 Вывод/tusur/1/Коваль Григорий Александрович.docx 42 1 Вывод/tusur/1/Кудрявцева Екатерина Евгеньевна.docx 59 1 Вывод/tusur/1/Владислав Фёдоров Юрьевич.docx 65 1 Вывод/tusur/2/Стрюков Станислав Александрович.docx 22 2 Вывод/tusur/1/Таюрский Александр Андреевич.docx 57 1 Вывод/tusur/2/Алиев Марат .docx 25 2 Вывод/tusur/2/Капустин Максим Александрович.docx 31 2 Вывод/tusur/1/Медянкин Владислав Константинович.docx 72 1 Вывод/tusur/1/Логинов Кирилл .docx 65 1 Вывод/tusur/1/Воробьева Александра Алексеевна.docx 71 1 Вывод/tusur/2/Федькин Максим Дмитриевич.docx 23 2 Вывод/tusur/1/Кин Анастасия Васильевна.docx 63 1 Вывод/tusur/2/Фоминых Софья Алексеевна.docx 37 2 Вывод/tusur/2/Карелин Дмитрий Викторович.docx 38 2 Вывод/tusur/1/Нигматулина Полина Рустамовна.docx 68 1 Вывод/tusur/2/Рыжков Максим Павлович.docx 35 2 Вывод/tusur/1/Филиппова Дарья Сергеевна.docx 68 1 Вывод/tusur/1/Никуленок Екатерина Сергеевна.docx 55 1 Вывод/tusur/1/Пугачев Виктор Павлович.docx 64 1 Вывод/tusur/2/Погребной Владимир Дмитриевич.docx 35 2 Вывод/tusur/1/Каменский Михаил Александрович.docx 51 1 Вывод/tusur/2/Кузьмина Алиса Евгеньевна.docx 25 2 Вывод/tusur/1/Потапов Егор Сергеевич.docx 55 1 Вывод/tusur/1/Панова Алина Андреевна.docx 42 1 Вывод/tusur/1/Максименко Иван Владимирович.docx 54 1 Вывод/tusur/1/Хабаров Антон Романович.docx 56 1 Вывод/tusur/1/Дегтерев Илья Павлович.docx 57 1 Вывод/tusur/1/Шмидт Эрик Александрович.docx 73 1 Вывод/tusur/2/Крылов Никита Сергеевич.docx 37 2 Вывод/tusur/1/Шапошников Игорь Денисович.docx 65 1 Вывод/tusur/1/Макаров Александр Александрович.docx 77 1 Вывод/tusur/1/Викин Олег Октаевич.docx 55 1 Вывод/tusur/1/Коровкин Никита Алексеевич.docx 73 1 Вывод/tusur/1/Коровкин Данила Алексеевич.docx 48 1 Вывод/tusur/2/Бузов Данила Сергеевич.docx 25 2 Вывод/tusur/1/Егорова Юлия Александровна.docx 56 1 Вывод/tusur/1/Чувашова Вера Андреевна.docx 63 1 Вывод/tusur/1/Тимошкин Никита Евгеньевич.docx 59 1 Вывод/tusur/2/Хен Данил Дмитриевич.docx 19 2 Вывод/tusur/1/Лаптева Ксения .docx 51 1 Вывод/tusur/1/Маратова Амина Маратовна.docx 55 1 Вывод/tusur/1/Куприянова Жанна Сергеевна.docx 63 1 Вывод/tusur/1/Коржов Денис Олегович.docx 43 1 Вывод/tusur/2/Мусин Тимур Куатжанович.docx 21 2 Вывод/tusur/1/Кузнецов Алексей Олегович.docx 72 1 Вывод/tusur/1/Цыбенов Аюр Булатович.docx 60 1 Вывод/tusur/1/Кологривова Кологривова Михайловна.docx 79 1 Вывод/tusur/1/Лобова Анастасия Александровна.docx 53 1 Вывод/tusur/1/Лунев Лев Александрович.docx 55 1 Вывод/tusur/2/Васильев Александр Сергеевич.docx 28 2 Вывод/tusur/1/Репников Никита Иванович.docx 43 1 Вывод/tusur/2/Скитович Андрей Сергеевич.docx 17 2 Вывод/tusur/2/Окушко Сергей Вячеславович.docx 26 2 Вывод/tusur/2/Мацкевич Никита Андреевич.docx 5 2 Вывод/tusur/1/Плотников Данил Романович.docx 64 1 Вывод/tusur/1/Овчарук Виталина Витальевна.docx 69 1 Вывод/tusur/1/Нефедов Данила Сергеевич.docx 81 1 Вывод/tusur/2/Корневский Даниил Дмитриевич.docx 38 2 Вывод/tusur/1/Тарасов Тарасов Сергеевич.docx 65 1 Вывод/tusur/2/Колбышева Екатерина Олеговна.docx 33 2 Вывод/tusur/2/Трякшин Андрей Андреевич.docx 32 2 Вывод/tusur/1/Глотов Даниил Дмитриевич.docx 52 1 Вывод/tusur/2/Бурдовицина Ульяна Александровна.docx 39 2 Вывод/tusur/2/Булавин Кристиан Александрович.docx 27 2 Вывод/tusur/1/Фоминых Алексей .docx 40 1 Вывод/tusur/1/Исайченко Никита Евгеньевич.docx 76 1 Вывод/tusur/1/Луговская Ирина Алексеевна.docx 60 1 Вывод/tusur/2/Акайкин Максим Дмитриевич.docx 18 2 Вывод/tusur/1/Алехина Юлия Андреевна.docx 62 1 Вывод/tusur/1/Дёмин Антон Андреевич.docx 68 1 Вывод/tusur/1/Сафонова Тамара Александровна.docx 48 1 Вывод/tusur/2/Буханцов Владислав Валериевич.docx 38 2 Вывод/tusur/2/Болобан Никита Андреевич.docx 32 2 Вывод/tusur/1/Кравцов Юрий Вадимович.docx 56 1 Вывод/tusur/2/Демчева Елизавета Максимовна.docx 22 2 Вывод/tusur/2/Худяков Александр Иванович.docx 35 2 Вывод/tusur/1/Ноздренко Владислав Евгеньевич.docx 67 1 Вывод/tusur/1/Юдин Данила Андреевич.docx 54 1 Вывод/tusur/2/Губайдулина Юлия Юрьевна.docx 35 2 Вывод/tusur/2/Новосёлов Александр Александрович.docx 20 2 Вывод/tusur/1/Хилдыхароева Карина Исаевна.docx 65 1 Вывод/tusur/1/Беклемешева Юлия Геннадьевна.docx 65 1 Вывод/tusur/1/Иванов Данил Валентинович.docx 53 1 Вывод/tusur/1/Тришина Дарья Геннадьевна.docx 58 1 Вывод/tusur/2/Пантелеев Егор Валериевич.docx 29 2 Вывод/tusur/2/Боодей Буян Омакович.docx 35 2 Вывод/tusur/1/Гринев Алексей Ярославович.docx 77 1 Вывод/tusur/1/Самойлов Данил Александрович.docx 57 1 Вывод/tusur/2/Сердюкова Анна Александровна.docx 30 2 Вывод/tusur/1/Цой Владислав Александрович.docx 44 1 Вывод/tusur/1/Абдуллин Руслан Наильевич.docx 67 1 Вывод/tusur/1/Горкальцева Алёна .docx 53 1 Вывод/tusur/1/Кузнецова Полина Ивановна.docx 64 1 Вывод/tusur/1/Шеф Дмитрий Игоревич.docx 45 1 Вывод/tusur/1/Скурихина Владислава Сергеевна.docx 74 1 Вывод/tusur/1/Олейников Максим Дмитриевич.docx 66 1 Вывод/tusur/1/Яценко Татьяна Евгеньевна.docx 70 1 Вывод/tusur/1/Дей Данил Владимирович.docx 79 1 Вывод/tusur/1/Сумин Артём Сергеевич.docx 68 1 Вывод/tusur/1/Мельниченко Павел Вадимович.docx 51 1 Вывод/tusur/1/Унжаков Тихон Эдуардович.docx 67 1 Вывод/tusur/1/Охезин Андрей Алексеевич.docx 49 1 Вывод/tusur/1/Хватов Вадим Вячеславович.docx 65 1 Вывод/tusur/1/Демченко Максим Алексеевич.docx 45 1 Вывод/tusur/1/Харитонов Данил Максимович.docx 40 1 Вывод/tusur/1/Козлов Кирилл Максимович.docx 49 1 Вывод/tusur/2/Потапов Ярослав Владимирович.docx 19 2 Вывод/tusur/2/Панасюк Кирилл Александрович.docx 30 2 Вывод/tusur/2/Ситников Александр Александрович.docx 10 2 Вывод/tusur/2/Калугин Андрей Александрович.docx 26 2 Вывод/tusur/1/Осипов Егор Ильич.docx 59 1 Вывод/tusur/1/Лушников Денис Алексеевич.docx 56 1 Вывод/tusur/1/Зенкин Дмитрий Александрович.docx 61 1 Вывод/tusur/2/Каратаев Алдияр Асанович.docx 37 2 Вывод/tusur/1/Степанов Александр Николаевич.docx 75 1 Вывод/tusur/1/Захарова Вероника Владимировна.docx 44 1 Вывод/tusur/1/Поддубошин Василий Викторович.docx 52 1 Вывод/tusur/1/Коробкин Юрий Андреевич.docx 62 1 Вывод/tusur/1/Загородникова Елизавета Евгеньевна.docx 46 1 Вывод/tusur/1/Монгуш Дорду Орланович.docx 68 1 Вывод/tusur/2/Иванова Ирина Александровна.docx 24 2 Вывод/tusur/2/Прикацина Анастасия Ивановна.docx 24 2 Вывод/tusur/2/Барышев Александр Романович.docx 30 2 Вывод/tusur/1/Карцев Егор Сергеевич.docx 44 1 Вывод/tusur/2/Кривошеин Ярослав Леонидович.docx 28 2 Вывод/tusur/1/Яцков Павел Сергеевич.docx 54 1 Вывод/tusur/2/Засядкин Алексей Игоревич.docx 35 2 Вывод/tusur/1/Безруков Александр Михайлович.docx 59 1 Вывод/tusur/1/Владимир Горбунов Владимирович.docx 46 1 Вывод/tusur/1/Вичканов Георгий Владимирович.docx 55 1 Вывод/tusur/1/Шкрум Антон Валерьевич.docx 58 1 Вывод/tusur/1/Бохтин Роберт Байрамович.docx 52 1 Вывод/tusur/1/Астафьев Максим Антонович.docx 56 1 Вывод/tusur/1/Часовских Елена Дмитриевна.docx 44 1 Вывод/tusur/1/Вавилов Александр Александрович.docx 62 1 Вывод/tusur/2/Харуцкий Иван Юрьевич.docx 37 2 Вывод/tusur/1/Строев Александр Владимирович.docx 54 1 Вывод/tusur/2/Нигмашев Арсен Алиханович.docx 27 2 Вывод/tusur/1/Щетинин Артур Дмитриевич.docx 45 1 Вывод/tusur/1/Семиколенов Илья .docx 54 1 Вывод/tusur/1/Митрохин Александр Андреевич.docx 71 1 Вывод/tusur/1/Лукьянов Вячеслав Евгеньевич.docx 60 1 Вывод/tusur/1/Жоодатбеков Дастан Омурнасипович.docx 43 1 Вывод/tusur/2/Машарова Яна Андреевна.docx 17 2 Вывод/tusur/2/Ермоленко Александра Сергеевна.docx 13 2 Вывод/tusur/1/Витковский Валерий Сергеевич.docx 45 1 Вывод/tusur/1/Шабанова Анастасия Андреевна.docx 53 1 Вывод/tusur/2/Егунов Ярослав Алексеевич.docx 35 2 Вывод/tusur/1/Бессонова Александра Вячеславовна.docx 67 1 Вывод/tusur/1/Загорская Софья Игоревна.docx 47 1 Вывод/tusur/1/Лопатин Данил Алексеевич.docx 44 1 Вывод/tusur/1/Баталов Егор Евгеньевич.docx 58 1 Вывод/tusur/1/Абрамов Кирилл Олегович.docx 42 1 Вывод/tusur/2/Имыкшенов Александр Викторович.docx 24 2 Вывод/tusur/2/Ведерникова Любовь Евгеньевна.docx 28 2 Вывод/tusur/1/Сидорова Анастасия Александровна.docx 54 1 Вывод/tusur/1/Кушнеров Кирилл Валерьевич.docx 57 1 Вывод/tusur/1/Туравинин Никита Сергеевич.docx 49 1 Вывод/tusur/1/Бобылева Анастасия Евгеньевна.docx 47 1 Вывод/tusur/1/Пастушков Вадим Денисович.docx 44 1 Вывод/tusur/1/Коваленко Владислав Алексеевич.docx 62 1 Вывод/tusur/1/Мишин Кирилл Алексеевич.docx 52 1 Вывод/tusur/1/Носков Всеволод Вениаминович.docx 64 1 Вывод/tusur/1/Хусаинов Тахир Наильевич.docx 49 1 Вывод/tusur/1/Наместников Дмитрий Александрович.docx 41 1 Вывод/tusur/1/Ягодзинская Александра Максимовна.docx 65 1 Вывод/tusur/1/Ермаков Арсений Дмитриевич.docx 59 1 Вывод/tusur/2/Лукьянова Анастасия Вадимовна.docx 37 2 Вывод/tusur/1/Фокина Александра Олеговна.docx 45 1 Вывод/tusur/2/Колотова Александра Сергеевна.docx 28 2 Вывод/tusur/2/Девочкин Данил Александрович.docx 3 2 Вывод/tusur/1/Сидоров Марк Евгеньевич.docx 51 1 Вывод/tusur/2/Ахмадеев Вадим Маратович.docx 18 2 Вывод/tusur/2/Варнавский Богдан Вячеславович.docx 26 2 Вывод/tusur/1/Немова Дарья Витальевна.docx 56 1 Вывод/tusur/1/Мухортов Андрей Дмитриевич.docx 41 1 Вывод/tusur/1/Борисов Дмитрий Витальевич.docx 71 1 Вывод/tusur/2/Сорокин Сергей Александрович.docx 15 2 Вывод/tusur/1/Арчаков Аюб Муссаевич.docx 70 1 Вывод/tusur/1/Гельгинберг Алексей Владиславович.docx 49 1 Вывод/tusur/2/Ильинична Ирина Афанасьева.docx 39 2 Вывод/tusur/2/Неумейков Семён .docx 39 2 Вывод/tusur/2/Шардаков Владислав Антонович.docx 36 2 Вывод/tusur/1/Романов Данил Игоревич.docx 62 1 Вывод/tusur/1/Видоменко Иван Владиславович.docx 69 1 Вывод/tusur/1/Гущин Михаил Александрович.docx 44 1 Вывод/tusur/2/Миняев Денис Александрович.docx 38 2 Вывод/tusur/1/Волков Александр Владимирович.docx 40 1 Вывод/tusur/2/Куликов Игорь Романович.docx 26 2 Вывод/tusur/1/Гумеров Владислав Викторович.docx 46 1 Вывод/tusur/1/Попова Анна Ивановна.docx 54 1 Вывод/tusur/2/Топоров Александр Дмитриевич.docx 35 2 Вывод/tusur/1/Вильчинский Вадим Денисович.docx 64 1 Вывод/tusur/1/Иванов Вячеслав Анатольевич.docx 45 1 Вывод/tusur/1/Кусков Кирилл Алексеевич.docx 76 1 Вывод/tusur/1/Матвеев Кирилл Васильевич.docx 41 1 Вывод/tusur/1/Деев Максим Александрович.docx 60 1 Вывод/tusur/1/Кобзев Сергей Алексеевич.docx 44 1 Вывод/tusur/1/Шуцько Данила Дмитриевич.docx 54 1 Вывод/tusur/1/Шульга Алексей Дмитриевич.docx 47 1 Вывод/tusur/1/Федосеенко Андрей Евгеньевич.docx 50 1 Вывод/tusur/1/Плаксин Антон Олегович.docx 43 1 Вывод/tusur/2/Бислингер Сергей Викторович.docx 28 2 Вывод/tusur/2/Гарматина Алина Олеговна.docx 37 2 Вывод/tusur/1/Чибриков Матвей Дмитриевич.docx 47 1 Вывод/tusur/1/Толкачев Илья Евгеньевич.docx 52 1 Вывод/tusur/1/Нагорняк Виктор Николаевич.docx 43 1 Вывод/tusur/1/Зубцова Елизавета Викторовна.docx 57 1 Вывод/tusur/1/Коноплёва Ольга Михайловна.docx 69 1 Вывод/tusur/1/Акашев Роман Александрович.docx 58 1 Вывод/tusur/1/Чувин Андрей Дмитриевич.docx 57 1 Вывод/tusur/1/Орлов Никита Валерьевич.docx 54 1 Вывод/tusur/2/Болотов Данил Михайлович.docx 25 2 Вывод/tusur/2/Федоров Роман Михайлович.docx 14 2 Вывод/tusur/2/Соловьева Галина Александровна.docx 24 2 Вывод/tusur/2/Катетунов Максим .docx 23 2 Вывод/tusur/1/Боровиков Максим Максимович.docx 45 1 Вывод/tusur/2/Мандриков Денис Юрьевич.docx 12 2 Вывод/tusur/1/Пряхин Данил Сергеевич.docx 57 1 Вывод/tusur/1/Петрушин Павел Александрович.docx 55 1 Вывод/tusur/1/Рыжов Евгений Игоревич.docx 52 1 Вывод/tusur/1/Подъяблонский Даниил .docx 40 1 Вывод/tusur/1/Королев Виталий Евгеньевич.docx 67 1 Вывод/tusur/1/Маташков Фома Викторович.docx 58 1 Вывод/tusur/1/Петрова Ольга Владиславовна.docx 68 1 Вывод/tusur/1/Струтинский Александр Игоревич.docx 55 1 Вывод/tusur/1/Матюша Вадим Алексеевич.docx 80 1 Вывод/tusur/1/Пахместеров Михаил .docx 46 1 Вывод/tusur/2/Христенко Роман Викторович.docx 19 2 Вывод/tusur/2/Бычихин Артём Андреевич.docx 38 2 Вывод/tusur/1/Петровский Егор .docx 51 1 Вывод/tusur/2/Колесников Владислав Сергеевич.docx 17 2 Вывод/tusur/2/Залогов Александр Евгеньевич.docx 39 2 Вывод/tusur/1/Галушко Павел Андреевич.docx 57 1 Вывод/tusur/2/Семёнов Никита Витальевич.docx 17 2 Вывод/tusur/2/Медведев Сергей Алексеевич.docx 36 2 Вывод/tusur/2/Кобзева Анастасия Олеговна.docx 31 2 Вывод/tusur/1/Кузнецов Андрей Владиславович.docx 71 1 Вывод/tusur/2/Осипов Александр Владимирович.docx 36 2 Вывод/tusur/1/Семенов Виталий Вадимович.docx 48 1 Вывод/tusur/2/Конгар Батый Белекович.docx 25 2 Вывод/tusur/2/Базавлук Олег Александрович.docx 31 2 Вывод/tusur/1/Ашихмин Максим Александрович.docx 52 1 Вывод/tusur/1/Рыбин Дмитрий Андреевич.docx 54 1 Вывод/tusur/2/Сошкин Антон Николаевич.docx 39 2 Вывод/tusur/2/Липовцев Дмитрий .docx 31 2 Вывод/tusur/1/Кривенко Владислав Владимирович.docx 51 1 Вывод/tusur/1/Куаме Яо Эммануэль Жуниор .docx 40 1 Вывод/tusur/2/Сергеев Сергей Викторович.docx 11 2 Вывод/tusur/2/Киреев Даниил Алексеевич.docx 31 2 Вывод/tusur/1/Ашмаров Марк .docx 52 1 Вывод/tusur/1/Быструшкин Евгений Михайлович.docx 44 1 Вывод/tusur/1/Ринчинов Аюр Олегович.docx 52 1 Вывод/tusur/2/Карбышев Денис Николаевич.docx 34 2 Вывод/tusur/1/Косарев Никита Александрович.docx 71 1 Вывод/tusur/1/Гуляр Мария Вадимовна.docx 50 1 Вывод/tusur/1/Чаштыг Омак Олегович.docx 62 1 Вывод/tusur/1/Черявко Егор Евгеньевич.docx 57 1 Вывод/tusur/1/Автономов Никита Сергеевич.docx 59 1 Вывод/tusur/2/Сидоренко Михаил Антонович.docx 30 2 Вывод/tusur/1/Захаркин Максим Валерьевич.docx 60 1 Вывод/tusur/1/Горохова Марина Евгеньевна.docx 68 1 Вывод/tusur/2/Марков Константин Николаевич.docx 13 2 Вывод/tusur/1/Виниченко Глеб Юрьевич.docx 41 1 Вывод/tusur/1/Грахович Владимир Владимирович.docx 61 1 Вывод/tusur/1/Коновалов Михаил Сергеевич.docx 51 1 Вывод/tusur/1/Романов Вячеслав Викторович.docx 51 1 Вывод/tusur/2/Болотников Павел Юрьевич.docx 14 2 Вывод/tusur/1/Кошечко Дарья Евгеньевна.docx 77 1 Вывод/tusur/2/Семенов Кирилл Олегович.docx 27 2 Вывод/tusur/2/Адаменко Егор Александрович.docx 39 2 Вывод/tusur/2/Новицкий Роман Александрович.docx 31 2 Вывод/tusur/2/Трихин Владислав Дмитриевич.docx 38 2 Вывод/tusur/1/Мочеков Данил Максимович.docx 61 1 Вывод/tusur/1/Ховалыг Айгуля Александровна.docx 72 1 Вывод/tusur/1/Шварц Екатерина Игоревна.docx 51 1 Вывод/tusur/1/Криницкая Татьяна Дмитриевна.docx 91 1 Вывод/tusur/1/Цыденов Баир Зоригтуевич.docx 64 1 Вывод/tusur/2/Липов Егор Сергеевич.docx 32 2 Вывод/tusur/1/Сороковиков Владимир Эдуардович.docx 42 1 Вывод/tusur/1/Ажичаков Александр Андреевич.docx 41 1 Вывод/tusur/1/Васильева Ксения Витальевна.docx 60 1 Вывод/tusur/1/Патраев Данила Александрович.docx 63 1 Вывод/tusur/1/Яхно Максим Дмитриевич.docx 43 1 Вывод/tusur/1/Ерёмин Богдан Евгеньевич.docx 51 1 Вывод/tusur/1/Тряпицин Сергей Андреевич.docx 57 1 Вывод/tusur/2/Горбунов Владимир Алексеевич.docx 37 2 Вывод/tusur/1/Полухин Денис Александрович.docx 54 1 Вывод/tusur/1/Черемисина Божена Игоревна.docx 57 1 Вывод/tusur/1/Горбунов Роман Андреевич.docx 69 1 Вывод/tusur/2/Черненко Виктор Евгеньевич.docx 20 2 Вывод/tusur/1/Ерлыков Владислав Александрович.docx 43 1 Вывод/tusur/2/Столяров Михаил Валерьевич.docx 32 2 Вывод/tusur/2/Толочкин Георгий Романович.docx 24 2 Вывод/tusur/2/Колуганов Сергей Сергеевич.docx 24 2 Вывод/tusur/2/Лобков Виктор Сергеевич.docx 15 2 Вывод/tusur/1/Мармышев Кирилл Евгеньевич.docx 60 1 Вывод/tusur/2/Султанов Руслан Евгеньевич.docx 29 2 Вывод/tusur/1/Зылев Дмитрий Александрович.docx 65 1 Вывод/tusur/1/Осетров Сергей Андреевич.docx 44 1 Вывод/tusur/2/Сафонов Владислав Михайлович.docx 33 2 Вывод/tusur/2/Нертик Никита Алексеевич.docx 31 2 Вывод/tusur/2/Иваничев Даниил Денисович.docx 38 2 Вывод/tusur/2/Неборский Мирон Евгеньевич.docx 26 2 Вывод/tusur/1/Яшков Матвей Сергеевич.docx 55 1 Вывод/tusur/2/Науменко Данил Николаевич.docx 22 2 Вывод/tusur/1/Лошманов Даниил Дмитриевич.docx 46 1 Вывод/tusur/1/Ермоленко Татьяна Анатольевна.docx 50 1 Вывод/tusur/1/Абрамов Максим Максимович.docx 44 1 Вывод/tusur/2/Фелингер Владимир Александрович.docx 25 2 Вывод/tusur/1/Фатеев Михаил Владиславович.docx 73 1 Вывод/tusur/1/Пестов Андрей Андреевич.docx 55 1 Вывод/tusur/1/Браун Вячеслав Александрович.docx 49 1 Вывод/tusur/2/Хасанова Тамила Ильдаровна.docx 27 2 Вывод/tusur/2/Семёнов Кирилл Михайлович.docx 39 2 Вывод/tusur/2/Зельчан Иван Романович.docx 19 2 Вывод/tusur/1/Поздеева Марина Александровна.docx 44 1 Вывод/tusur/2/Монгуш Субудай Сылдысович.docx 22 2 Вывод/tusur/1/Куцык Евгений Дмитриевич.docx 47 1 Вывод/tusur/1/Морозов Тимур .docx 79 1 Вывод/tusur/1/Ли Егор .docx 49 1 Вывод/tusur/1/Морозкова Диана Александровна.docx 60 1 Вывод/tusur/1/Махрина Татьяна Ильинична.docx 62 1 Вывод/tusur/1/Забавнова Валерия Александровна.docx 68 1 Вывод/tusur/2/Шляк Илья Александрович.docx 15 2 Вывод/tusur/1/Колесникова Дарья Дмитриевна.docx 69 1 Вывод/tusur/1/Зыкова Арина Алексеевна.docx 58 1 Вывод/tusur/2/Хохлов Станислав Юрьевич.docx 29 2 Вывод/tusur/2/Москаленко Вячеслав Дмитриевич.docx 13 2 Вывод/tusur/1/Миков Виктор Алексеевич.docx 40 1 Вывод/tusur/1/Переворочаев Антон Андреевич.docx 49 1 Вывод/tusur/1/Храпов Никита Сергеевич.docx 45 1 Вывод/tusur/2/Хлебников Вениамин Александрович.docx 38 2 Вывод/tusur/2/Озерова Полина Игоревна.docx 34 2 Вывод/tusur/1/Варламова Кристина Александровна.docx 51 1 Вывод/tusur/2/Вишняков Никита Сергеевич.docx 29 2 Вывод/tusur/2/Алимпьев Иван Александрович.docx 33 2 Вывод/tusur/1/Чипигин Андрей Дмитриевич.docx 52 1 Вывод/tusur/2/Дегтярев Алексей Евгеньевич.docx 10 2 Вывод/tusur/1/Митрошин Дмитрий Эдуардович.docx 56 1 Вывод/tusur/1/Реутов Константин Андреевич.docx 46 1 Вывод/tusur/2/Стрелец Дарья Олеговна.docx 5 2 Вывод/tusur/2/Ложкина Алина Андреевна.docx 20 2 Вывод/tusur/1/Невзоров Денис Владимирович.docx 65 1 Вывод/tusur/2/Муравьева Арина Андреевна.docx 17 2 Вывод/tusur/2/Кунгаа Айдар Орланович.docx 39 2 Вывод/tusur/2/Посадский Ярослав Борисовия.docx 36 2 Вывод/tusur/1/Романов Георгий Павлович.docx 65 1 Вывод/tusur/1/Чевга Андрей Андреевич.docx 40 1 Вывод/tusur/1/Механошина Светлана Алексеевна.docx 49 1 Вывод/tusur/2/Дудник Дарья Андреевна.docx 39 2 Вывод/tusur/1/Прокопов Александр Дмитриевич.docx 67 1 Вывод/tusur/2/Пыхтин Валерий Николаевич.docx 31 2 Вывод/tusur/2/Виноградов Максим Даниилович.docx 33 2 Вывод/tusur/2/Дорошенко Виктор Алексеевич.docx 30 2 Вывод/tusur/1/Идамжапов Намжил Чимитович.docx 67 1 Вывод/tusur/1/Топоровский Максим Алексеевич.docx 43 1 Вывод/tusur/2/Слюзков Игорь Александрович.docx 31 2 Вывод/tusur/1/Блохин Роман Игоревич.docx 51 1 Вывод/tusur/1/Власов Владимир Андреевич.docx 46 1 Вывод/tusur/1/Толстов Александр Андреевич.docx 57 1 Вывод/tusur/1/Душкин Илья Дмитриевич.docx 48 1 Вывод/tusur/1/Горюнов Александр Дмитриевич.docx 55 1 Вывод/tusur/1/Лобасенко Александр Владимирович.docx 56 1 Вывод/tusur/1/Азизов Асхат Алимджанович.docx 78 1 Вывод/tusur/1/Стародубцев Игорь Алексеевич.docx 69 1 Вывод/tusur

In [78]:
import os
for filename in os.listdir('Вывод/tusur'):
    if filename not in string:
        print(filename)

Артаа Эртине Адыгжыевич.docx
Варанкин Илья Данилович.docx
Веснин Алексей Юрьевич.docx
Иванов Иван Иванович.docx
Иванов Иван Сергеевич.docx
Изранов Сергей Сергеевич.docx
Калиев Кымбат Сымбатович.docx
Киселёв Вячеслав Алексеевич.docx
Клипов Алексей Вадимович.docx
Коленкова Виктория Евгеньевна.docx
крукр кру укркур.docx
Кули-Оглы Марат Хайдарович.docx
Локтионов Артём Эдуардович.docx
Мартыненко Егор Дмитриевич.docx
Онопко Виктор Витальевич.docx
Процких Никита Сергеевич.docx
Саксонов Константин Сергеевич.docx
Скороходова Анастасия Станиславовна.docx
Слюсарь Ангелина Сергеевна.docx
Терешкин Иван Андреевич.docx
Трофимов Игорь Васильевич.docx
Тютяков Максим Романович.docx
Хайбулин Никита Сергеевич.docx
Хорошилов Дмитрий Александрович.docx
Цыганкова Анастасия Витальевна.docx
Чеблуков Никита Евгеньевич.docx

In [40]:
df['count'] = df['name'].apply(lambda x: x.count(' '))

In [132]:
from tqdm import tqdm

In [134]:
import docx
result = []
for filename in tqdm(os.listdir('Вывод/tusur')[2:]):
    doc = docx.Document('Вывод/tusur/'+filename)
    table = doc.tables[0]
    data = []
    keys = None
    for i, row in enumerate(table.rows):
        text = (cell.text for cell in row.cells)

        # Establish the mapping based on the first row
        # headers; these will become the keys of our dictionary
        if i == 0:
            keys = tuple(text)
            continue

        # Construct a dictionary for this row, mapping
        # keys to values for this row
        row_data = dict(zip(keys, text))
        data.append(row_data)

    email = list(data[3].values())[1]
    context = {'city': 'tusur', 'name': filename[:-5], 'email': email, 'score': list(data[3].keys())[0][list(data[3].keys())[0].index(': ')+2:]}
    for key in ['univer', 'phone', 'socialmedia']:
        context[key] = max(df0[df0['ma_email'] == email][key], key=len)

    result.append([context['name'], context['email'], context['city'], context['univer'], context['phone'], context['socialmedia'], context['score']])

result_title = "Первичный балл test"
result_pts = pd.DataFrame(result)
result_pts.sort_values(6, ascending = False, inplace = True)
result_pts.rename(columns={0: 'ФИО', 1: 'Почта', 2: 'Город', 3: 'Курс', 4: 'Телефон', 5: 'Сеть', 6: 'Первичный балл'}, inplace = True)
result_pts.insert(0, "№", range(1, len(result_pts) + 1))
result_pts.to_excel("Вывод/{}.xlsx".format(result_title))
#print_df(result_pts, "Вывод/{}.docx".format(result_title))
#drive_write(result_title, folder_root_id, "Вывод/" + result_title, replace = False)

100%|████████████████████████████████████████████████████████████████████████████████| 514/514 [02:07<00:00,  4.02it/s]

In [136]:
df0 = pd.read_excel('Nice2MeetYou.xlsx', dtype = str, keep_default_na = False)
df0['gorodprojivaniya'].replace('/', ';', regex=True, inplace=True)
df0['ma_email'] = df0['ma_email'].str.lower()
key_short = 'tusur'
ma_emails = df0[df0['referer']=='https://techpreneur-school.ru/intro-concepts-of-techpreneurship-{}/test/nice2meetyou'.format(key_short)]['ma_email'].unique()
#ma_emails = ['seleznev.ks@sygma.ru']
emails = [email for email in ma_emails if 'test' not in email]
emails.index('lisichka_iv@mail.ru')

1093

In [137]:
emails.index('nastyapav03@gmail.com')

1092

In [ ]:
from collections import Counter as Cl
Cl(dff['ФИО']).most_common

In [188]:
dff = pd.read_excel('Вывод/tusur1.xlsx')
#dff = dff.groupby('ФИО', group_keys=False).apply(lambda x: x.loc[x['Первичный балл'].idxmax()])
from collections import Counter as Cl
Cl(dff['ФИО']).most_common(10)

[('Ховалыг Айгуля Александровна', 2),
 ('Лыков Иван ', 2),
 ('Челтыгмашева Айана Алексеевна', 2),
 ('Гуртовая Полина Андреевна', 1),
 ('Адаменко Павел Алексеевич', 1),
 ('Байгулова Татьяна Алексеевна', 1),
 ('Пушилин Кирилл Анатольевич', 1),
 ('Бабаева Амина Расуловна', 1),
 ('Козлова Алиса ', 1),
 ('Алферова Татьяна Павловна', 1)]

In [186]:
dff.sort_values('Первичный балл', ascending = False, inplace = True)
dff["№"] = range(1, len(dff) + 1)

In [187]:
dff.to_excel('123.xlsx')

In [170]:
dff = pd.read_excel('Вывод/tusur1.xlsx')
dff = dff.groupby('ФИО', group_keys=False).apply(lambda x: x.loc[x['Первичный балл'].idxmax()])

In [23]:
names_raw = """Александр Лукин Вадимович
Алина Матюшина Алексеевна
Екатерина Шевченко Тарасовна
Анастасия Тронина
Юлия Карелина Валерьевна
Александра Лагнер
Павел Параев Алексеевич
Николай Латышев Андреевич
Максим Сыромятников Денисович"""
names = names_raw.split('\n')
surnames = [name.split(' ')[1]+' '+name.split(' ')[0] for name in names]
surnames

['Лукин Александр',
 'Матюшина Алина',
 'Шевченко Екатерина',
 'Тронина Анастасия',
 'Карелина Юлия',
 'Лагнер Александра',
 'Параев Павел',
 'Латышев Николай',
 'Сыромятников Максим']

In [34]:
import os
for folder in os.listdir('yandex')[:]:
    if [filename for filename in os.listdir('yandex/'+folder+'/data') if any([s_name in filename for s_name in surnames])] != []:
        print(folder, [filename for filename in os.listdir('yandex/'+folder+'/data') if any([s_name in filename for s_name in surnames])])
        for file in [filename for filename in os.listdir('yandex/'+folder+'/data') if any([s_name in filename for s_name in surnames])]:
            shutil.copy('yandex/'+folder+'/data/'+file, 'final/'+folder)

11 сентября 2021_Томск_ТГУ ['_игрок_Карелина Юлия.html', '_игрок_Латышев Николай.html', '_игрок_Сыромятников Максим.html', '_игрок_Шевченко Екатерина.html']
14 июня 2021 Екатеринбург_Урфу ['_игрок_Лукин Александр.html']
17 октября 2020 Нижний Новгород ['_игрок_Матюшина Алина.html']
20 октября 2021 Новосибирск НГТУ ['_игрок_Лагнер Александра.html', '_игрок_Параев Павел.html', '_игрок_Тронина Анастасия.html']

In [37]:
import os
for folder in os.listdir('final'):
    for filename in os.listdir('final/'+folder):
        print(folder, filename)

11 сентября 2021_Томск_ТГУ _игрок_Карелина Юлия.html
11 сентября 2021_Томск_ТГУ _игрок_Латышев Николай.html
11 сентября 2021_Томск_ТГУ _игрок_Сыромятников Максим.html
11 сентября 2021_Томск_ТГУ _игрок_Шевченко Екатерина.html
14 июня 2021 Екатеринбург_Урфу _игрок_Лукин Александр.html
17 октября 2020 Нижний Новгород _игрок_Матюшина Алина.html
20 октября 2021 Новосибирск НГТУ _игрок_Лагнер Александра.html
20 октября 2021 Новосибирск НГТУ _игрок_Параев Павел.html
20 октября 2021 Новосибирск НГТУ _игрок_Тронина Анастасия.html